DD-1093  Test
DANS-KNAW/dd-validate-dans-bag pull request #14
Opened 2022-09-30 12:35 UTC by jo-pol

Fixes DD-1093  Test

# Description of changes

# How to test

# Related PRs
(Add links)
*

# Notify
@DANS-KNAW/dataversedans

2022-10-04 12:14 UTC, ericdevries commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +                    log.debug("not covered despite constructors that set to null");
some constructors in rules set error message to null, check if that should happen

2022-10-04 12:28 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceIntegrationTest.java
>          assertTrue(response.getIsCompliant());
The previous test indicates that this bag should not be valid in a WITH_DATASTATION_CONTEXT context, but it does

2022-10-04 12:29 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceIntegrationTest.java
> +        assertEquals("java.io.ByteArrayInputStream", response.getEntity().toString().replaceAll("@.*","")); // TODO can't we return a more descriptive body?
Error messages should be better

2022-10-04 12:30 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceIntegrationTest.java
>              assertEquals(400, response.getStatus());
test return message

2022-10-04 12:33 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceTest.java
> +            assertEquals(500, response.getStatus());
This currently returns a 400 bad request

2022-10-04 14:40 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceIntegrationTest.java
> +        assertEquals("java.io.ByteArrayInputStream", response.getEntity().toString().replaceAll("@.*","")); // TODO can't we return a more descriptive body?
Error message is actually OK here; the fault lies at how the response is serialized to string. If you just do response.getEntity() it will return the ByteArrayInputStream which should then be converted to a string (new String(response.getEntity().readAllBytes() or something).

Even better would be to request a String entity from it, like so:

```
response.readEntity(String.class)
```

Or even better: 
```
System.out.println("RESPONSE: " + response.readEntity(BadRequestException.class));
```
Which will then output the following error message:

```
RESPONSE: javax.ws.rs.BadRequestException: Request could not be processed: Extracted zip does not contain a directory
```

2022-10-04 14:41 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceIntegrationTest.java
>          assertTrue(response.getIsCompliant());
The zip method assumed a stand_alone context, which does not make sense. Added a method to allow to pass an optional request argument `level`

2022-10-04 14:44 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceTest.java
> +            assertEquals(500, response.getStatus());
It did not mock the `fileService.getFirstDirectory()` method so it threw a NPE

2022-10-04 14:59 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/resource/ValidateResourceTest.java
>  class ValidateResourceTest {
After some consideration I believe it is quite useful for testing the behaviour of the ValidateResource in its own context.

2022-10-12 09:53 UTC, janvanmansum requested changes
@jo-pol , @ericdevries : I don't think the builder is a good idea here, so I am not going to merge this PR. On the other hand, the renaming of the test files seems reasonable, as the validator is not concerned with audiences for example.

2022-10-12 09:53 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/validatedansbag/core/service/RuleEngineServiceImpl.java
> -            new NumberedRule("1.1.1", bagRules.bagIsValid()),
@jo-pol : what is the advance of a builder here? It seems to me that it only makes the code harder to read.

2022-10-12 09:53 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/validatedansbag/core/service/RuleEngineServiceImpl.java
> -            new NumberedRule("3.1.10(a)", bagRules.ddmMustHaveRightsHolderDeposit(), DepositType.DEPOSIT, List.of("3.1.1")),
@jo-pol : is this why you introduced the builder? If you look left and right you can see that it is very clear already tha this parameter sets a DepositType.

2022-10-12 09:53 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +            throw new InternalServerErrorException("Internal server error: " + e.getMessage(), e);
I don't see why you would want to include the exception message here. I think 500 messages should not give details to the outside world.

2022-10-12 11:01 UTC, ericdevries commented on src/main/java/nl/knaw/dans/validatedansbag/core/service/RuleEngineServiceImpl.java
> -            new NumberedRule("1.1.1", bagRules.bagIsValid()),
I actually introduced this to migate a possible issue we had with a different object, so I had my refactoring-goggles on and went a bit overboard. I actually wanted to get rid of the large amount of constructor variants. This is my original implementation: https://github.com/DANS-KNAW-jp/dd-validate-dans-bag/pull/1/files#diff-7b9b08d42605e7b55a703de312cc6d4446abcfc5608e64f440dadd28f10e8d43

Slightly different but functionally the same.

2022-10-13 07:02 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +            throw new InternalServerErrorException("Internal server error: " + e.getMessage(), e);
Again this was Eric's PR on mine and I overlooked it. Elaborating `validateFormDataWithInternalServerError` shows the reason will be returned in the body of the response as `{"code":500,"message":"Internal server error: Error deleting directory"}`.

2022-10-13 07:37 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +            throw new InternalServerErrorException("Internal server error: " + e.getMessage(), e);
I thought I mentioned not being happy with `BagValidatorRule.validate` throwing an `Exception` It should throw something like `RuleException` so it can be caught like `BagNotFoundException` in `ValidateResource`. Now we are returning internal errors what are actually bad requests.

2022-10-13 14:43 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +        catch (SAXException e) {
It might be better to catch this at the first line of `validatePath`. It is a violation of not configured dependency on `xmlFileConformsToSchema`.

2022-10-20 11:31 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/core/rules/BagRulesImpl.java
> +                    "Bag is not valid: %s", e.getMessage().replace(path.toString() + "/", "")
To not expose paths to a bag on the server to the client. Brute force implementation.

2022-10-20 11:33 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java
> +            violationMessage = XmlRules.toRuleMsg(e);
If the dependencies on schema validation are properly configured. This is a fall back in case the dependencies are missing, as they where.

2022-10-20 11:34 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/core/rules/XmlRules.java
> +    public static String toRuleMsg (SAXParseException e) {
whoops.

2022-10-20 12:09 UTC, jo-pol commented on src/main/java/nl/knaw/dans/validatedansbag/core/rules/XmlRules.java
> +    public static String toRuleMsg (SAXParseException e) {
Sorry, one commit was not pushed.

The usages seem string context to me. Perhaps you want another home for this method, in scala I might have chosen a package object. Oh, perhaps another name for the method.

https://github.com/DANS-KNAW/dd-validate-dans-bag/blob/10609dd7ea7336a054375004b311a6abd4ee5715/src/main/java/nl/knaw/dans/validatedansbag/core/rules/XmlRulesImpl.java#L71

and

https://github.com/DANS-KNAW/dd-validate-dans-bag/blob/afa32b61719b0f267b2832e1dc4e882bd9383088/src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java#L146

https://github.com/DANS-KNAW/dd-validate-dans-bag/blob/afa32b61719b0f267b2832e1dc4e882bd9383088/src/main/java/nl/knaw/dans/validatedansbag/resource/ValidateResource.java#L161

2022-12-21 12:56 UTC, closed without merging