Invavlid XML is also considered an ERROR
DANS-KNAW/dd-validate-dans-bag pull request #15
Opened 2022-10-06 11:38 UTC by ericdevries

Fixes DD-1152

# Description of changes

# How to test

# Related PRs
(Add links)
*

# Notify
@DANS-KNAW/dataversedans

2022-10-10 08:42 UTC, jo-pol commented on src/test/java/nl/knaw/dans/validatedansbag/core/rules/XmlRulesImplTest.java
> +        var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
I don't see where this variable is used.

2022-10-10 12:37 UTC, ericdevries commented on src/test/java/nl/knaw/dans/validatedansbag/core/rules/XmlRulesImplTest.java
> +        var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
You are correct

2022-10-11 15:48 UTC, janvanmansum commented on src/test/java/nl/knaw/dans/validatedansbag/core/rules/XmlRulesImplTest.java
> +        var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
@ericdevries : then shouldn't the variable be removed?

2022-10-12 09:32 UTC, janvanmansum requested changes
LGTM, tested it and worked as expected. @ericdevries : please, address the comment about the unused variable. Otherwise, ready for merge.

2022-10-12 10:13 UTC, janvanmansum approved these changes

2022-10-12 10:13 UTC, merged